services:
  backend:
    build:
      context: ./value-investing-backend/valueinvesting
      target: prod
    container_name: backend
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
    restart: on-failure 
    env_file:
      - .env
      - ./value-investing-backend/valueinvesting/.env
    networks:
      - value_investing_app_ntw

  db:
    image: postgres:17
    container_name: postgres_db
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 20s
    networks:
      - value_investing_app_ntw

  redis:
    image: redis:8
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"] # enables AOF persistence
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - value_investing_app_ntw

  celery_worker:
    build:
      context: ./value-investing-backend/valueinvesting
      target: prod
    container_name: celery_worker
    entrypoint: ["celery", "-A", "valueinvesting", "worker", "--loglevel=info", "--concurrency=4"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure
    env_file:
      - .env
      - ./value-investing-backend/valueinvesting/.env
    networks:
      - value_investing_app_ntw

  frontend:
    build: ./value-investing-frontend/value-investing
    container_name: frontend
    ports:
      - 80:80 # serve static build files via nginx
    networks:
      - value_investing_app_ntw

volumes:
  postgres_db:
  redis_data:

networks:
  value_investing_app_ntw:
    driver: bridge
