services:
  backend:
    build:
      context: ./value-investing-backend/valueinvesting
      target: dev
    volumes:
      - ./value-investing-backend/valueinvesting:/app

  # pgadmin to be used in dev for easiert data visualization
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80" # access PgAdmin in browser
    networks:
      - value_investing_app_ntw
    depends_on:
      - db
    
  db:
    ports:
      - "5433:5432"

  celery_worker:
    build:
      context: ./value-investing-backend/valueinvesting
      target: dev
    volumes:
      - ./value-investing-backend/valueinvesting:/app

  frontend:
    build:
      context: ./value-investing-frontend/value-investing
      target: dev
    ports:
      - 3000:3000 # React dev server
    networks:
      - value_investing_app_ntw
    env_file:
      - ./value-investing-frontend/value-investing/.env.dev
    volumes:
      - ./value-investing-frontend/value-investing:/app # mount local code for hot reload
      - /app/node_modules # prevent overwriting container node_modules
    command: ["npm", "run", "start"] # run React dev server
