# Generated by Django 5.1.7 on 2026-07-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfs_dj', '0016_alter_incomestatementannual_shares_diluted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedcompanies',
            name='currency',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Currency'),
        ),
    ]
