# Generated by Django 5.1.7 on 2026-09-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfs_dj', '0017_alter_tradedcompanies_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheetannual',
            name='reporting_currency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Reporting Currency'),
        ),
        migrations.AddField(
            model_name='balancesheetquarter',
            name='reporting_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementannual',
            name='reporting_currency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Reporting Currency'),
        ),
        migrations.AddField(
            model_name='cashflowstatementquarter',
            name='reporting_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementannual',
            name='reporting_currency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Reporting Currency'),
        ),
        migrations.AddField(
            model_name='incomestatementquarter',
            name='reporting_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='screenerdata',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency'),
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(db_index=True, max_length=10)),
                ('to_currency', models.CharField(db_index=True, max_length=10)),
                ('rate', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
    ]
