# Generated by Django 5.1.7 on 2026-09-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfs_dj', '0018_balancesheetannual_reporting_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedcompanies',
            name='company_type',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Company Type'),
        ),
    ]
