# Generated by Django 5.1.7 on 2026-06-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='ocr_s3_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
