# Generated by Django 5.1.7 on 2026-06-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst_reports', '0002_userupload_ocr_s3_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='llm_s3_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
