# Generated by Django 5.1.7 on 2026-06-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst_reports', '0003_userupload_llm_s3_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
