# Generated by Django 5.1.7 on 2026-06-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst_reports', '0004_userupload_retry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('scanning', 'Scanning Document'), ('extracting', 'Extracting Key Data'), ('done', 'Done'), ('failed', 'Failed')], default='uploaded', max_length=50),
        ),
    ]
