# Generated by Django 5.1.7 on 2026-06-18 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst_reports', '0005_alter_userupload_status'),
        ('quickfs_dj', '0016_alter_incomestatementannual_shares_diluted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='document_type',
            field=models.CharField(blank=True, choices=[('annual_report', 'Annual Report'), ('quarterly_report', 'Quarterly Report'), ('earnings_call', 'Earnings Call'), ('investor_presentation', 'Investor Presentation'), ('analyst_report', 'Analyst Report'), ('proxy_statement', 'Proxy Statement'), ('news_article', 'News Article'), ('filing', 'Filing'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AnalystReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('pdf_s3_key', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qfs_symbol', models.ForeignKey(db_column='qfs_symbol', on_delete=django.db.models.deletion.CASCADE, to='quickfs_dj.tradedcompanies', to_field='qfs_symbol')),
                ('source_uploads', models.ManyToManyField(blank=True, related_name='analyst_reports', to='analyst_reports.userupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
