# Generated by Django 5.1.7 on 2026-06-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst_reports', '0006_userupload_document_type_analystreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
