# Generated by Django 5.1.7 on 2026-07-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst_reports', '0007_userupload_error_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userupload',
            name='llm_s3_key',
        ),
        migrations.AlterField(
            model_name='userupload',
            name='document_type',
            field=models.CharField(blank=True, choices=[('annual_report', 'Annual Report'), ('quarterly_report', 'Quarterly Report'), ('earnings_call', 'Earnings Call'), ('investor_presentation', 'Investor Presentation'), ('analyst_report', 'Analyst Report'), ('news_article', 'News Article'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('scanning', 'Scanning Document'), ('done', 'Done'), ('failed', 'Failed')], default='uploaded', max_length=50),
        ),
    ]
